local constants = require("main.modules.constants")
local logic = require("main.modules.logic")

function init(self)
	self.score = 0
	msg.post(".",  "acquire_input_focus")
end

local STONE_WIDTH = constants.STONE_WIDTH
local STONE_HEIGHT = constants.STONE_HEIGHT

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		print(action.x, action.y)
		print(go.get_world_position("board").x)

		factory.create("main#first-stone-factory", vmath.vector3(
		action.x,
		action.y,
		1
		))
			
		x = math.floor(action.x / STONE_WIDTH)
		y = math.floor(action.y / STONE_HEIGHT)
		if not logic.can_put(x, y) then
			return
		end
		logic.put(x, y)
		factory.create(
			logic.turn() == 1 and "main#first-stone-factory" or "main#second-stone-factory",
			vmath.vector3(x * env.STONE_WIDTH, y * env.STONE_HEIGHT, 0)
		)
		local is_finish = logic.is_finish()
		print('is_finish: ', is_finish)
	end
end
