local constants = require("main.modules.constants")
local logic = require("main.modules.logic")
local ai = require("main.modules.ai")
local rendercam = require "rendercam.rendercam"

function init(self)
	self.score = 0
	msg.post(".",  "acquire_input_focus")
	-- rendercam.zoom(3)
	msg.post("/board#result", "disable")
end

local STONE_WIDTH = constants.STONE_WIDTH
local STONE_HEIGHT = constants.STONE_HEIGHT
local PADDING_LEFT = constants.PADDING_LEFT
local PADDING_BOTTOM =constants.PADDING_BOTTOM

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		pos =rendercam.screen_to_world_2d(action.screen_x, action.screen_y)		
		go.set_position(pos, ".")	
	end
end

function update_finish()
	msg.post("/next-block#sprite", "play_animation", { id = logic.turn() == 1 and hash("red-stone") or hash("blue-stone") })

	local is_finish = logic.is_finish()
	if is_finish > 0 then
		print('is_finish: ', is_finish)
		if is_finish == 1 then
			label.set_text("/board#result", "Red Win!!")
		elseif is_finish == 2 then
			label.set_text("/board#result", "Blue Win!!")
		else
			label.set_text("/board#result", "Draw")
		end
		msg.post("/board#result", "enable")
	end
	return is_finish
end

function on_message(self, message_id, message, sender)
	if message_id == hash("touch") then
		print("cursor.on_message", message_id, sender, x, y)
		x, y = logic.find_position_by_id(msg.url(sender).path)
		go.set_position(vmath.vector3(
			-1000, -1000, 1
		), ".")	

		if not logic.can_put(x, y) then
			print('not can put')
			return
		end
		print('can put')
		logic.put(x, y)

		sound.play("#tap")

		factory.create(
			logic.turn() == 1 and "main#first-stone-factory" or "main#second-stone-factory",
			vmath.vector3(
				x * STONE_WIDTH * 4 + PADDING_LEFT, y * STONE_HEIGHT * 4 + PADDING_BOTTOM, 0
			),
			nil,
			nil,
			4.0
		)

		local finish = update_finish()

		if finish == 0 then
			pos = ai.ai_think()
			print("ai pos: " .. pos[1] .. ", " .. pos[2])
			print(logic.can_put(pos[1], pos[2]))
			logic.put(pos[1], pos[2])
			local id = factory.create(
					logic.turn() == 1 and "main#first-stone-factory" or "main#second-stone-factory",
					vmath.vector3(
					pos[1] * STONE_WIDTH * 4 + PADDING_LEFT, pos[2] * STONE_HEIGHT * 4 + PADDING_BOTTOM, 0
				),
				nil,
				nil,
				4.0
			)
			table.insert(stones, id)		
		end

		update_finish()		
	end
end